services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - outlier_network
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "5432", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  commcare_data_export_outlierdetect:
    container_name: commcare_data_export_outlierdetect
    build: commcare_data_export_outlierdetect/
    env_file:
      - ./commcare_data_export_outlierdetect/.env
    networks:
      - outlier_network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  outlier_network:
    driver: bridge
